management:
  endpoints:
    web:
      exposure:
        include: "health,info,env,beans,logfile"

ogcapi:
  debug:
    elasticsearch-explain-enabled: true

data-discovery-ai:
  host: https://data-discovery-ai.edge.aodn.org.au

es-indexer:
  host: https://es-indexer.edge.aodn.org.au

geonetwork4:
  host: https://geonetwork.edge.aodn.org.au

elasticsearch:
  semantic:
    enabled: false
