name: Build and Test

on:
  workflow_dispatch:

permissions:
  id-token: write   # JWT
  contents: read    # actions/checkout

jobs:
  ogcapi_build:
    runs-on: ubuntu-latest
    environment: tfintegration
    steps:
      - name: CheckoutClone repo
        uses: actions/checkout@v4


      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.ROLE_ARN }}
          role-session-name: GitHub_to_AWS_OIDC
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
  
      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: ${{ vars.ECR_REPOSITORY }}
